---
- name: restart node_exporter
  debug: msg="restarting node_exporter with {{ prometheus_supervisor }}"
  changed_when: true
  notify: "{{ prometheus_supervisor }} restart node_exporter"

- name: reload node_exporter
  debug: msg="reloading node_exporter with {{ prometheus_supervisor }}"
  changed_when: true
  notify: "{{ prometheus_supervisor }} reload node_exporter"
